### ISSUE TITLE
setWindowSize usage

### ISSUE THREAD

**Issue by jykae** [flyingfisher/selenium-html-js-converter#16]
@flyingfisher Am I doing this right, or is this bug?

Usage:

```
module.exports = function testAPINFCatalogue(_browser, _options) {

    browser = _browser;
    browser.setWindowSize('800 600');
```

Result:

```
Error: [setWindowSize("800 600")] Unexpected data in simpleCallback.
    at exports.newError (/Users/jykae/work/apinf-testing/node_modules/wd/lib/utils.js:139:13)
    at /Users/jykae/work/apinf-testing/node_modules/wd/lib/callbacks.js:39:12
    at /Users/jykae/work/apinf-testing/node_modules/wd/lib/webdriver.js:169:5
    at Request._callback (/Users/jykae/work/apinf-testing/node_modules/wd/lib/http-utils.js:78:7)
    at Request.self.callback (/Users/jykae/work/apinf-testing/node_modules/request/request.js:121:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/jykae/work/apinf-testing/node_modules/request/request.js:985:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/jykae/work/apinf-testing/node_modules/request/request.js:936:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by flyingfisher** [comment]
A strange problem. I have checked code, there is no problem round setWindowSize.
Could you give me some example to reproduce this bug?

**Comment by jykae** [comment]
Pushed full examples upstream, https://github.com/apinf/apinf-testing/pull/11

Inspected also your code round that function, and it looked fine and short function. Maybe something with wd-sync, it points to /wd/lib/utils.js

@flyingfisher what is difference with wd-sync & wd-sync-raw? I used wd-sync, could issue be with that? Usage says to use wd-sync-raw https://github.com/flyingfisher/selenium-html-js-converter#usage Example for running requires wd-sync, https://github.com/flyingfisher/selenium-html-js-converter#to-run-the-javascript

Thanks for quick answer :)

**Comment by FirassKoubaa** [comment]
still with no solution ??

**Comment by flyingfisher** [comment]
Sorry for late answer, I just have changed my job during the time.
And the 'wd-sync-raw' is a fork of 'wd-sync', they are similiar.

**Comment by flyingfisher** [comment]
I have done a test in test/testsuit1.html. And there is no problem.

You can run 'node test/test.js' to test it manually. It seems to work fine.

**Comment by flyingfisher** [comment]
This is the right usage:
```browser.setWindowSize(800, 600);```
